apiVersion: v1
data:
  ASPNETCORE_ENVIRONMENT: EX_Production
  DescontoOnlineConfiguration__BaseAddressDescontoOnline: http://api-desconto-extra.api-desconto-prd.svc.cluster.local
  DescontoOnlineConfiguration__TextoDescontoMarketplace: no PIX
  DescontoOnlineConfiguration__TimeOutDesconto: "1000"
kind: ConfigMap
metadata:
  annotations:
    artifact.spinnaker.io/location: api-preco-b2c-prd
    artifact.spinnaker.io/name: api-preco-extra
    artifact.spinnaker.io/type: kubernetes/configMap
    artifact.spinnaker.io/version: ""
    devops.k8s.io/branch: release/3.21
    devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
    devops.k8s.io/component-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-name: cnova-preco
    devops.k8s.io/component-plataform: 'Baixa '
    devops.k8s.io/component-repository-url: https://github.com/viavarejo-internal/cnova-preco
    devops.k8s.io/component-squad: SQ PREÇO
    devops.k8s.io/component-system0-description: ""
    devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
    devops.k8s.io/component-system0-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-system0-name: '[Serviço de Preço]'
    devops.k8s.io/component-system0-product0-description: Ser uma plataforma que centralize
      todas as precificações 1P, em todos os canais da companhia, bem como gerenciar
      possíveis divergências de Preços para que o Comercial e Pricing tenham visão
      completa para tomada de decisão.
    devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
    devops.k8s.io/component-system0-product0-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-system0-product0-name: Precificação de Produto
    devops.k8s.io/component-tribe: TB PREÇO
    devops.k8s.io/flag: via
    devops.k8s.io/nexus-url: https://nexus.viavarejo.com.br/repository/charts/api-preco-b2c/3.21-1/deploy-via-prd.yaml
    devops.k8s.io/project-name: api-preco-b2c
    devops.k8s.io/repository: api-preco-b2c
    devops.k8s.io/servicenow-task-number: CHG0316585
    devops.k8s.io/spinnaker: "true"
    devops.k8s.io/squad: Preço
    devops.k8s.io/tribe: Inteligência Comercial
    devops.k8s.io/version: 3.21-1
    devops.k8s.io/xl-release-start-date: Mon Apr 22 08:45:06 BRT 2024
    devops.k8s.io/xl-release-title: '[Preço] api-preco-b2c - 3.21-1'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ASPNETCORE_ENVIRONMENT":"EX_Production","DescontoOnlineConfiguration__BaseAddressDescontoOnline":"http://api-desconto-extra.api-desconto-prd.svc.cluster.local","DescontoOnlineConfiguration__TextoDescontoMarketplace":"no PIX","DescontoOnlineConfiguration__TimeOutDesconto":"1000"},"kind":"ConfigMap","metadata":{"annotations":{"artifact.spinnaker.io/location":"api-preco-b2c-prd","artifact.spinnaker.io/name":"api-preco-extra","artifact.spinnaker.io/type":"kubernetes/configMap","artifact.spinnaker.io/version":"","devops.k8s.io/branch":"release/3.21","devops.k8s.io/component-id":"9a277506-7244-45ed-9713-1388f0755c15","devops.k8s.io/component-journey":"JN INTELIGÊNCIA COMERCIAL","devops.k8s.io/component-name":"cnova-preco","devops.k8s.io/component-plataform":"Baixa ","devops.k8s.io/component-repository-url":"https://github.com/viavarejo-internal/cnova-preco","devops.k8s.io/component-squad":"SQ PREÇO","devops.k8s.io/component-system0-description":"","devops.k8s.io/component-system0-id":"1c7ea6fa-c95e-481a-b1f0-6609c0a69120","devops.k8s.io/component-system0-journey":"JN INTELIGÊNCIA COMERCIAL","devops.k8s.io/component-system0-name":"[Serviço de Preço]","devops.k8s.io/component-system0-product0-description":"Ser uma plataforma que centralize todas as precificações 1P, em todos os canais da companhia, bem como gerenciar possíveis divergências de Preços para que o Comercial e Pricing tenham visão completa para tomada de decisão.","devops.k8s.io/component-system0-product0-id":"4d552446-6825-4d51-9976-362156f21c22","devops.k8s.io/component-system0-product0-journey":"JN INTELIGÊNCIA COMERCIAL","devops.k8s.io/component-system0-product0-name":"Precificação de Produto","devops.k8s.io/component-tribe":"TB PREÇO","devops.k8s.io/flag":"via","devops.k8s.io/nexus-url":"https://nexus.viavarejo.com.br/repository/charts/api-preco-b2c/3.21-1/deploy-via-prd.yaml","devops.k8s.io/project-name":"api-preco-b2c","devops.k8s.io/repository":"api-preco-b2c","devops.k8s.io/servicenow-task-number":"CHG0316585","devops.k8s.io/spinnaker":"true","devops.k8s.io/squad":"Preço","devops.k8s.io/tribe":"Inteligência Comercial","devops.k8s.io/version":"3.21-1","devops.k8s.io/xl-release-start-date":"Mon Apr 22 08:45:06 BRT 2024","devops.k8s.io/xl-release-title":"[Preço] api-preco-b2c - 3.21-1","moniker.spinnaker.io/application":"pricing","moniker.spinnaker.io/cluster":"configMap api-preco-extra","strategy.spinnaker.io/versioned":"false","viavarejo.com.br/app":"api-preco","viavarejo.com.br/team":"pricing"},"labels":{"app":"api-preco-extra","app.kubernetes.io/deployed-by":"spinnaker-artifact-nexus","app.kubernetes.io/environment":"prd","app.kubernetes.io/managed-by":"spinnaker","app.kubernetes.io/name":"pricing","app.kubernetes.io/part-of":"api-preco-extra","app.kubernetes.io/project-name":"api-preco-b2c","app.kubernetes.io/stage":"stable","app.kubernetes.io/version":"3-21-1","devops.k8s.io/component-id":"9a277506-7244-45ed-9713-1388f0755c15","devops.k8s.io/component-journey":"jn-inteligencia-comercial","devops.k8s.io/component-name":"cnova-preco","devops.k8s.io/component-plataform":"baixa","devops.k8s.io/component-squad":"sq-preco","devops.k8s.io/component-system0-id":"1c7ea6fa-c95e-481a-b1f0-6609c0a69120","devops.k8s.io/component-system0-journey":"jn-inteligencia-comercial","devops.k8s.io/component-system0-name":"servico-de-preco","devops.k8s.io/component-system0-product0-id":"4d552446-6825-4d51-9976-362156f21c22","devops.k8s.io/component-system0-product0-journey":"jn-inteligencia-comercial","devops.k8s.io/component-system0-product0-name":"precificacao-de-produto","devops.k8s.io/component-tribe":"tb-preco"},"name":"api-preco-extra","namespace":"api-preco-b2c-prd"}}
    moniker.spinnaker.io/application: pricing
    moniker.spinnaker.io/cluster: configMap api-preco-extra
    strategy.spinnaker.io/versioned: "false"
    viavarejo.com.br/app: api-preco
    viavarejo.com.br/team: pricing
  creationTimestamp: "2024-01-09T03:35:25Z"
  labels:
    app: api-preco-extra
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: pricing
    app.kubernetes.io/part-of: api-preco-extra
    app.kubernetes.io/project-name: api-preco-b2c
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 3-21-1
    devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
    devops.k8s.io/component-journey: jn-inteligencia-comercial
    devops.k8s.io/component-name: cnova-preco
    devops.k8s.io/component-plataform: baixa
    devops.k8s.io/component-squad: sq-preco
    devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
    devops.k8s.io/component-system0-journey: jn-inteligencia-comercial
    devops.k8s.io/component-system0-name: servico-de-preco
    devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
    devops.k8s.io/component-system0-product0-journey: jn-inteligencia-comercial
    devops.k8s.io/component-system0-product0-name: precificacao-de-produto
    devops.k8s.io/component-tribe: tb-preco
  name: api-preco-extra
  namespace: api-preco-b2c-prd
  resourceVersion: "1451172195"
  uid: 1435d34b-670d-4bd1-a1af-aca8566391df
