apiVersion: v1
data:
  AUTH_AZAD_CLIENT_ID: 3e55e003-15d9-4b19-9c19-f194f04e9f29
  AUTH_AZAD_TENANT_ID: 5a86b3fb-4213-49cd-b4d6-be91482ad3c0
  COMERCIAL_BONIFICACAO_API_URL: https://comercial-bonificacao-prd.viavarejo.com.br/vv-comercial/api/v1
  COMERCIAL_BONIFICACAO_CLIENT_APP: comercialapp:V3rb@s-@pP-$3cRe7
  COMERCIAL_BONIFICACAO_ENV_TYPE: PRD
  COMERCIAL_BONIFICACAO_NGX_URL: https://bonificacao.viavarejo.com.br/
  TZ: America/Sao_Paulo
kind: ConfigMap
metadata:
  annotations:
    app.via.com.br/branch: release/2.5.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-redesign-ngx/2.5.0-41/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-redesign-ngx
    app.via.com.br/repository: comercial-bonificacao-redesign-ngx
    app.via.com.br/servicenow-task-number: CHG0307852
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 2.5.0-41
    app.via.com.br/xl-release-start-date: Wed Mar 06 13:14:16 BRT 2024
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-redesign-ngx
      - 2.5.0-41'
    artifact.spinnaker.io/location: bonificacao-prd
    artifact.spinnaker.io/name: comercial-bonificacao-redesign-ngx-gc7d47fhht
    artifact.spinnaker.io/type: kubernetes/configMap
    artifact.spinnaker.io/version: ""
    moniker.spinnaker.io/application: bonificacao
    moniker.spinnaker.io/cluster: configMap comercial-bonificacao-redesign-ngx-gc7d47fhht
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-redesign-ngx
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: bonificacao
    app.kubernetes.io/part-of: comercial-bonificacao-redesign-ngx-gc7d47fhht
    app.kubernetes.io/project-name: comercial-bonificacao-redesign-ngx
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 2.5.0-41
  name: comercial-bonificacao-redesign-ngx-gc7d47fhht
  namespace: bonificacao-prd
