apiVersion: v1
data:
  COMERCIAL_BONIFICACAO_API_LOGGER_REST_ENABLED: "false"
  JVM_OPTS: -Xmx2G -Xms1536m
  LOGGING_LEVEL_SPRING_SECURITY: TRACE
  LOGGING_LEVEL_SPRING_WEB: TRACE
  LOGGING_LEVEL_SPRING_WEB_FILTER: TRACE
  LOGGING_LEVEL_VV: TRACE
  SFTP_VV_REMOTE_DIRECTORY: /share3/Gestao\ de\ Verbas/SIT
  VM_ARGS: -Dfile.encoding=UTF-8 -Duser.timezone=America/Buenos_Aires -Dspring.profiles.active=docker,scheduler
kind: ConfigMap
metadata:
  annotations:
    app.via.com.br/branch: release/6.7.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-api/6.7.0-9/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-api
    app.via.com.br/repository: comercial-bonificacao-api
    app.via.com.br/servicenow-task-number: CHG0282911
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 6.7.0-9
    app.via.com.br/xl-release-start-date: Wed Sep 27 14:03:02 BRT 2023
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-api - 6.7.0-9'
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-api
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/part-of: comercial-bonificacao-schedulers-app-c4bmkt8f28
    app.kubernetes.io/project-name: comercial-bonificacao-api
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 6.7.0-9
  name: comercial-bonificacao-schedulers-app-c4bmkt8f28
  namespace: bonificacao-prd
