apiVersion: v1
data:
  COMERCIAL_BONIFICACAO_ENV_TYPE: PRD
  COMERCIAL_BONIFICACAO_FORNECEDORES_API_URL: https://comercial-bonificacao-prd.viavarejo.com.br/vv-comercial
  COMERCIAL_BONIFICACAO_FORNECEDORES_CLIENT_APP: comercialapp:V3rb@s-@pP-$3cRe7
  COMERCIAL_BONIFICACAO_FORNECEDORES_NGX_URL: https://parceiros.viavarejo.com.br/
  TZ: America/Sao_Paulo
kind: ConfigMap
metadata:
  annotations:
    artifact.spinnaker.io/location: bonificacao-prd
    artifact.spinnaker.io/name: comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    artifact.spinnaker.io/type: kubernetes/configMap
    artifact.spinnaker.io/version: v000
    moniker.spinnaker.io/application: bonificacao
    moniker.spinnaker.io/cluster: configMap comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    moniker.spinnaker.io/sequence: "0"
  labels:
    app: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: bonificacao
    moniker.spinnaker.io/sequence: "0"
  name: comercial-bonificacao-fornecedores-ngx-kg65dcgh68-v000
  namespace: bonificacao-prd
