apiVersion: v1
data:
  COMERCIAL_BONIFICACAO_ENV_TYPE: PRD
  COMERCIAL_BONIFICACAO_FORNECEDORES_API_URL: https://comercial-bonificacao-prd.viavarejo.com.br/vv-comercial
  COMERCIAL_BONIFICACAO_FORNECEDORES_CLIENT_APP: comercialapp:V3rb@s-@pP-$3cRe7
  COMERCIAL_BONIFICACAO_FORNECEDORES_NGX_URL: https://parceiros.viavarejo.com.br/
  TZ: America/Sao_Paulo
kind: ConfigMap
metadata:
  annotations:
    app.via.com.br/branch: release/2.0.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-fornecedores-ngx/2.0.0-7/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-fornecedores-ngx
    app.via.com.br/repository: comercial-bonificacao-fornecedores-ngx
    app.via.com.br/servicenow-task-number: CHG0282032
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 2.0.0-7
    app.via.com.br/xl-release-start-date: Fri Sep 22 16:50:22 BRT 2023
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-fornecedores-ngx
      - 2.0.0-7'
    artifact.spinnaker.io/location: bonificacao-prd
    artifact.spinnaker.io/name: comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    artifact.spinnaker.io/type: kubernetes/configMap
    artifact.spinnaker.io/version: ""
    moniker.spinnaker.io/application: bonificacao
    moniker.spinnaker.io/cluster: configMap comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: bonificacao
    app.kubernetes.io/part-of: comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    app.kubernetes.io/project-name: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 2.0.0-7
  name: comercial-bonificacao-fornecedores-ngx-kg65dcgh68
  namespace: bonificacao-prd
