apiVersion: v1
data:
  COMERCIAL_BONIFICACAO_API_LOGGER_REST_ENABLED: "false"
  JVM_OPTS: -Xmx2G -Xms1536m
  LOGGING_LEVEL_SPRING_SECURITY: TRACE
  LOGGING_LEVEL_SPRING_WEB: TRACE
  LOGGING_LEVEL_SPRING_WEB_FILTER: TRACE
  LOGGING_LEVEL_VV: TRACE
  VM_ARGS: -Dfile.encoding=UTF-8 -Duser.timezone=America/Buenos_Aires -Dspring.profiles.active=docker,scheduler
kind: ConfigMap
metadata:
  labels:
    app: comercial-bonificacao-kafka-consumer
  name: comercial-bonificacao-schedulers-app-g455fh76gg
  namespace: bonificacao-prd
