apiVersion: v1
kind: PersistentVolume
metadata:
  name: sku-catalog
  labels:
    type: azure-blob
spec:
  storageClassName: blob-fuse-stgviastore
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
