apiVersion: v1
kind: PersistentVolume
metadata:
  name: sku-catalog
  labels:
    type: local
spec:
  storageClassName: blob-fuse-stgviastore
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
