apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         10
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Workers       5

    [INPUT]
        Name                tail
        Tag                 kube.*
        multiline.parser    docker, cri
        Buffer_Chunk_Size   2MB
        Buffer_Max_Size     10MB
        Mem_Buf_Limit       512MB
        Refresh_Interval    10
        Path                /var/log/containers/*.log
        Exclude_Path        /var/log/containers/api-oferta-feed-*.log,/var/log/containers/*gatekeeper-system_manager*.log,/var/log/containers/*tigera-operator_tigera-operator*.log,/var/log/containers/*_istio-proxy*.log,/var/log/containers/*_istio-init*.log,/var/log/containers/fluentd-*.log,/var/log/containers/calico-*.log,/var/log/containers/tunnelfront-*.log,/var/log/containers/kube-proxy-*.log,/var/log/containers/kubernetes-dashboard-*.log,/var/log/containers/metrics-server-*.log,/var/log/containers/coredns-*.log,/var/log/containers/dashboard-metrics-scraper-*.log,/var/log/containers/addon-http-application-routing-*.log,/var/log/containers/nginx-ingress-controller-*.log,/var/log/containers/tiller-deploy-*.log,/var/log/containers/oneagent-*.log,/var/log/containers/*-prometheus-*.log,/var/log/containers/data-collector-fluentd-*.log,/var/log/containers/local-volume-provisioner-*.log,/var/log/containers/logging-fluentd-*.log,/var/log/containers/node-exporter-*.log,/var/log/containers/ovs-*.log,/var/log/containers/sdn-*.log,/var/log/containers/sync-*.log,/var/log/containers/dynatrace-*.log, /var/log/containers/fluent*

    [FILTER]
        Name                Kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       l
        Keep_Log            Off
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude On
        Labels              Off
        Annotations         Off

    [OUTPUT]
        Name        kafka
        Match       *
        Brokers     evh-via-intcomercial-prd.servicebus.windows.net:9093
        Topics      aks-intcomercial
        Retry_Limit    1
        queue_full_retries 1
        rdkafka.request.required.acks 0
        rdkafka.request.timeout.ms 2000
        rdkafka.linger.ms 500
        rdkafka.message.max.bytes 41943040
        rdkafka.metadata.max.age.ms 5000
        rdkafka.queue.buffering.max.kbytes 100000
        rdkafka.socket.keepalive.enable true
        rdkafka.security.protocol SASL_SSL
        rdkafka.sasl.mechanism PLAIN
        rdkafka.sasl.username $ConnectionString
        rdkafka.sasl.password Endpoint=sb://evh-via-intcomercial-prd.servicebus.windows.net/;SharedAccessKeyName=fluentd-intcomercial;SharedAccessKey=njvAgc5I9sqPMVtA7TUVwUQ/Q9fOfWPZ2+AEhNfxVmI=

kind: ConfigMap
metadata:
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
  namespace: logging
