apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-kafka.conf
  input-kubernetes.conf: |
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        multiline.parser    docker, cri
        Exclude_Path        /var/log/containers/api-oferta-feed-*.log,/var/log/containers/*gatekeeper-system_manager*.log,/var/log/containers/*tigera-operator_tigera-operator*.log,/var/log/containers/*_istio-proxy*.log,/var/log/containers/*_istio-init*.log,/var/log/containers/fluentd-*.log,/var/log/containers/calico-*.log,/var/log/containers/tunnelfront-*.log,/var/log/containers/kube-proxy-*.log,/var/log/containers/kubernetes-dashboard-*.log,/var/log/containers/metrics-server-*.log,/var/log/containers/coredns-*.log,/var/log/containers/dashboard-metrics-scraper-*.log,/var/log/containers/addon-http-application-routing-*.log,/var/log/containers/nginx-ingress-controller-*.log,/var/log/containers/tiller-deploy-*.log,/var/log/containers/oneagent-*.log,/var/log/containers/*-prometheus-*.log,/var/log/containers/data-collector-fluentd-*.log,/var/log/containers/local-volume-provisioner-*.log,/var/log/containers/logging-fluentd-*.log,/var/log/containers/node-exporter-*.log,/var/log/containers/ovs-*.log,/var/log/containers/sdn-*.log,/var/log/containers/sync-*.log,/var/log/containers/dynatrace-*.log
        Mem_Buf_Limit       500MB
        Buffer_Chunk_Size   200M
        Buffer_Max_Size     400M
        Docker_Mode         On
        Ignore_Older        2h

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           Off
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude Off

    [FILTER]
        Name modify
        Match *
        Remove message
        Remove namespace_name
        Remove kubernetes.labels.*
        Remove tags

  output-kafka.conf: |
    [OUTPUT]
        Name        kafka
        Match       *
        Brokers     evh-via-intcomercial-prd.servicebus.windows.net:9093
        Topics      aks-intcomercial
        Retry_Limit    2
        rdkafka.security.protocol SASL_SSL
        rdkafka.sasl.mechanism PLAIN
        rdkafka.sasl.username $ConnectionString
        rdkafka.sasl.password Endpoint=sb://evh-via-intcomercial-prd.servicebus.windows.net/;SharedAccessKeyName=fluentd-intcomercial;SharedAccessKey=njvAgc5I9sqPMVtA7TUVwUQ/Q9fOfWPZ2+AEhNfxVmI=

kind: ConfigMap
metadata:
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
  namespace: logging
