apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    app.via.com.br/branch: release/6.7.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-api/6.7.0-9/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-api
    app.via.com.br/repository: comercial-bonificacao-api
    app.via.com.br/servicenow-task-number: CHG0282911
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 6.7.0-9
    app.via.com.br/xl-release-start-date: Wed Sep 27 14:03:02 BRT 2023
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-api - 6.7.0-9'
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "170"
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-api
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/part-of: comercial-bonificacao-api
    app.kubernetes.io/project-name: comercial-bonificacao-api
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 6.7.0-9
    deploymentconfig: comercial-bonificacao-api
    pod-template-hash: 7f7cbf7477
  name: comercial-bonificacao-api-7f7cbf7477
  namespace: bonificacao-prd
spec:
  replicas: 0
  selector:
    matchLabels:
      app: comercial-bonificacao-api
      pod-template-hash: 7f7cbf7477
  template:
    metadata:
      annotations:
        app.via.com.br/branch: release/6.7.0
        app.via.com.br/flag: via
        app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-api/6.7.0-9/deploy-via-prd.yaml
        app.via.com.br/project-name: comercial-bonificacao-api
        app.via.com.br/repository: comercial-bonificacao-api
        app.via.com.br/servicenow-task-number: CHG0282911
        app.via.com.br/spinnaker: "true"
        app.via.com.br/squad: Bonificação
        app.via.com.br/tribe: Inteligência Comercial
        app.via.com.br/version: 6.7.0-9
        app.via.com.br/xl-release-start-date: Wed Sep 27 14:03:02 BRT 2023
        app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-api
          - 6.7.0-9'
        automation.via/restartedAt: "2023-12-07T06:00:09.542358Z"
        kubectl.kubernetes.io/restartedAt: "2023-10-20T00:14:16-03:00"
        strategy.spinnaker.io/versioned: "false"
      creationTimestamp: null
      labels:
        app: comercial-bonificacao-api
        app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
        app.kubernetes.io/environment: prd
        app.kubernetes.io/part-of: comercial-bonificacao-api
        app.kubernetes.io/project-name: comercial-bonificacao-api
        app.kubernetes.io/stage: stable
        app.kubernetes.io/version: 6.7.0-9
        deploymentconfig: comercial-bonificacao-api
        pod-template-hash: 7f7cbf7477
    spec:
      containers:
      - env:
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              key: DATASOURCE_URL
              name: postgres-bonificacao
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: DATASOURCE_USERNAME
              name: postgres-bonificacao
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATASOURCE_PASSWORD
              name: postgres-bonificacao
        - name: SECURITY_JWT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SECURITY_JWT_CLIENT_ID
              name: jwt-bonificacao
        - name: SECURITY_JWT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SECURITY_JWT_CLIENT_SECRET
              name: jwt-bonificacao
        - name: SECURITY_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: SECURITY_JWT_SIGNING_KEY
              name: jwt-bonificacao
        - name: SECURITY_JWT_COMERCIAL_APP
          valueFrom:
            secretKeyRef:
              key: SECURITY_JWT_COMERCIAL_APP
              name: jwt-comercial
        - name: SECURITY_JWT_COMERCIAL_SECRET
          valueFrom:
            secretKeyRef:
              key: SECURITY_JWT_COMERCIAL_SECRET
              name: jwt-comercial
        - name: LN_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              key: LN_DATASOURCE_URL
              name: ln-bonificacao
        - name: LN_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: LN_DATASOURCE_USERNAME
              name: ln-bonificacao
        - name: LN_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LN_DATASOURCE_PASSWORD
              name: ln-bonificacao
        - name: LN_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            secretKeyRef:
              key: LN_DATASOURCE_DRIVER_CLASS_NAME
              name: ln-bonificacao
        - name: LN_TEST_WHILE_IDLE
          valueFrom:
            secretKeyRef:
              key: LN_TEST_WHILE_IDLE
              name: ln-bonificacao
        - name: LN_VALIDATION_QUERY
          valueFrom:
            secretKeyRef:
              key: LN_VALIDATION_QUERY
              name: ln-bonificacao
        - name: AZURE_ACTIVEDIRECTORY_SESSION_STATELESS
          valueFrom:
            secretKeyRef:
              key: AZURE_ACTIVEDIRECTORY_SESSION_STATELESS
              name: azure-ad-bonificacao
        - name: AZURE_ACTIVEDIRECTORY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_ACTIVEDIRECTORY_CLIENT_ID
              name: azure-ad-bonificacao
        - name: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
              name: azure-ad-bonificacao
        - name: AZURE_ACTIVEDIRECTORY_TENANT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_ACTIVEDIRECTORY_TENANT_ID
              name: azure-ad-bonificacao
        - name: AZURE_ACTIVEDIRECTORY_USER_GROUP_ALLOWED_GROUPS
          valueFrom:
            secretKeyRef:
              key: AZURE_ACTIVEDIRECTORY_USER_GROUP_ALLOWED_GROUPS
              name: azure-ad-bonificacao
        envFrom:
        - configMapRef:
            name: comercial-bonificacao-api-c2ch49b568
        image: harbor01.viavarejo.com.br/bonificacao/comercial-bonificacao-api:6.7.0-9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: comercial-bonificacao-api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 60
          successThreshold: 3
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 800m
            memory: 2250Mi
          requests:
            cpu: 100m
            memory: 750Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        agentpool: boniapp
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
