apiVersion: v1
kind: Pod
metadata:
  annotations:
    app.via.com.br/branch: release/2.0.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-fornecedores-ngx/2.0.0-7/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-fornecedores-ngx
    app.via.com.br/repository: comercial-bonificacao-fornecedores-ngx
    app.via.com.br/servicenow-task-number: CHG0282032
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 2.0.0-7
    app.via.com.br/xl-release-start-date: Fri Sep 22 16:50:22 BRT 2023
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-fornecedores-ngx
      - 2.0.0-7'
    artifact.spinnaker.io/location: bonificacao-prd
    artifact.spinnaker.io/name: comercial-bonificacao-fornecedores-ngx
    artifact.spinnaker.io/type: kubernetes/deployment
    artifact.spinnaker.io/version: ""
    automation.via/restartedAt: "2024-05-14T03:26:32.716215Z"
    kubectl.kubernetes.io/restartedAt: "2023-10-20T00:14:11-03:00"
    moniker.spinnaker.io/application: bonificacao
    moniker.spinnaker.io/cluster: deployment comercial-bonificacao-fornecedores-ngx
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: bonificacao
    app.kubernetes.io/part-of: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/project-name: comercial-bonificacao-fornecedores-ngx
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 2.0.0-7
    deploymentconfig: comercial-bonificacao-fornecedores-ngx
    pod-template-hash: 5ffc7b6877
  name: comercial-bonificacao-fornecedores-ngx-5ffc7b6877-v67d8
  namespace: bonificacao-prd
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: comercial-bonificacao-fornecedores-ngx-kg65dcgh68
    image: harbor01.viavarejo.com.br/bonificacao/bonificacao-prd/comercial-bonificacao-fornecedores-ngx:2.0.0-7
    livenessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 180
      timeoutSeconds: 2
    name: comercial-bonificacao-fornecedores-ngx
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: "0"
        memory: "0"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cdtrd
      readOnly: true
  nodeSelector:
    agentpool: boniapp
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: default
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-cdtrd
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
