apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2023-10-20T00:14:15-03:00"
  labels:
    app: comercial-bonificacao-pgbouncer
    pod-template-hash: 8449df68b6
  name: comercial-bonificacao-pgbouncer-8449df68b6-q2sb2
  namespace: bonificacao-prd
spec:
  containers:
  - image: harbor01.viavarejo.com.br/bonificacao/bonificacao-prd/comercial-bonificacao-pgbouncer:1.0.0-3
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - killall -INT pgbouncer && sleep 120
    livenessProbe:
      initialDelaySeconds: 180
      periodSeconds: 50
      tcpSocket:
        port: 5432
      timeoutSeconds: 2
    name: comercial-bonificacao-pgbouncer
    ports:
    - containerPort: 5432
    readinessProbe:
      tcpSocket:
        port: 5432
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - mountPath: /etc/pgbouncer
      name: configfiles
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-drmt6
      readOnly: true
  nodeSelector:
    app: bonoapp
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: default
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: configfiles
    secret:
      secretName: comercial-bonificacao-pgbouncer
  - name: kube-api-access-drmt6
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
