apiVersion: v1
kind: Pod
metadata:
  annotations:
    automation.via/restartedAt: "2024-05-14T03:26:32.592647Z"
    kubectl.kubernetes.io/restartedAt: "2024-02-01T00:20:51-03:00"
  labels:
    app: comercial-bonificacao-api
    deploymentconfig: comercial-bonificacao-schedulers-app
    pod-template-hash: 6b7f4c4f67
  name: comercial-bonificacao-schedulers-app-6b7f4c4f67-fqmtv
  namespace: bonificacao-prd
spec:
  containers:
  - env:
    - name: DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          key: DATASOURCE_URL
          name: postgres-bonificacao
    - name: DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          key: DATASOURCE_USERNAME
          name: postgres-bonificacao
    - name: DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: DATASOURCE_PASSWORD
          name: postgres-bonificacao
    - name: SECURITY_JWT_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: SECURITY_JWT_CLIENT_ID
          name: jwt-bonificacao
    - name: SECURITY_JWT_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: SECURITY_JWT_CLIENT_SECRET
          name: jwt-bonificacao
    - name: SECURITY_JWT_SIGNING_KEY
      valueFrom:
        secretKeyRef:
          key: SECURITY_JWT_SIGNING_KEY
          name: jwt-bonificacao
    - name: SECURITY_JWT_COMERCIAL_APP
      valueFrom:
        secretKeyRef:
          key: SECURITY_JWT_COMERCIAL_APP
          name: jwt-comercial
    - name: SECURITY_JWT_COMERCIAL_SECRET
      valueFrom:
        secretKeyRef:
          key: SECURITY_JWT_COMERCIAL_SECRET
          name: jwt-comercial
    - name: LN_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          key: LN_DATASOURCE_URL
          name: ln-bonificacao
    - name: LN_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          key: LN_DATASOURCE_USERNAME
          name: ln-bonificacao
    - name: LN_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: LN_DATASOURCE_PASSWORD
          name: ln-bonificacao
    - name: LN_DATASOURCE_DRIVER_CLASS_NAME
      valueFrom:
        secretKeyRef:
          key: LN_DATASOURCE_DRIVER_CLASS_NAME
          name: ln-bonificacao
    - name: LN_TEST_WHILE_IDLE
      valueFrom:
        secretKeyRef:
          key: LN_TEST_WHILE_IDLE
          name: ln-bonificacao
    - name: LN_VALIDATION_QUERY
      valueFrom:
        secretKeyRef:
          key: LN_VALIDATION_QUERY
          name: ln-bonificacao
    - name: AZURE_ACTIVEDIRECTORY_SESSION_STATELESS
      valueFrom:
        secretKeyRef:
          key: AZURE_ACTIVEDIRECTORY_SESSION_STATELESS
          name: azure-ad-bonificacao
    - name: AZURE_ACTIVEDIRECTORY_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: AZURE_ACTIVEDIRECTORY_CLIENT_ID
          name: azure-ad-bonificacao
    - name: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
          name: azure-ad-bonificacao
    - name: AZURE_ACTIVEDIRECTORY_TENANT_ID
      valueFrom:
        secretKeyRef:
          key: AZURE_ACTIVEDIRECTORY_TENANT_ID
          name: azure-ad-bonificacao
    - name: AZURE_ACTIVEDIRECTORY_USER_GROUP_ALLOWED_GROUPS
      valueFrom:
        secretKeyRef:
          key: AZURE_ACTIVEDIRECTORY_USER_GROUP_ALLOWED_GROUPS
          name: azure-ad-bonificacao
    envFrom:
    - configMapRef:
        name: comercial-bonificacao-schedulers-app-c4bmkt8f28
    image: harbor01.viavarejo.com.br/bonificacao/bonificacao-prd/comercial-bonificacao-api:6.5.0-6
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8090
      initialDelaySeconds: 60
      periodSeconds: 3600
      timeoutSeconds: 3600
    name: comercial-bonificacao-schedulers-app
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8090
      initialDelaySeconds: 20
      periodSeconds: 3600
      successThreshold: 3
      timeoutSeconds: 3600
    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bc5rk
      readOnly: true
  nodeSelector:
    agentpool: boniapp
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: default
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-bc5rk
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
