apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "30"
  labels:
    app: comercial-bonificacao-ngx
  name: comercial-bonificacao-ngx
  namespace: bonificacao-prd
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: comercial-bonificacao-ngx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-09-12T04:28:30Z"
      creationTimestamp: null
      labels:
        app: comercial-bonificacao-ngx
        deploymentconfig: comercial-bonificacao-ngx
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: comercial-bonificacao-ngx-9mb6mht5tb
        image: harbor01.viavarejo.com.br/bonificacao/bonificacao-prd/comercial-bonificacao-ngx:5.4.1-2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: comercial-bonificacao-ngx
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: bonoapp
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
