apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  labels:
    app: comercial-bonificacao-pgbouncer
  name: comercial-bonificacao-pgbouncer
  namespace: bonificacao-prd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: comercial-bonificacao-pgbouncer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-10-20T00:14:15-03:00"
      creationTimestamp: null
      labels:
        app: comercial-bonificacao-pgbouncer
    spec:
      containers:
      - image: harbor01.viavarejo.com.br/bonificacao/bonificacao-prd/comercial-bonificacao-pgbouncer:1.0.0-3
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - killall -INT pgbouncer && sleep 120
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 180
          periodSeconds: 50
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 2
        name: comercial-bonificacao-pgbouncer
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pgbouncer
          name: configfiles
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: bonoapp
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configfiles
        secret:
          defaultMode: 420
          secretName: comercial-bonificacao-pgbouncer
