apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    artifact.spinnaker.io/location: api-preco-b2c-hlg
    artifact.spinnaker.io/name: api-preco-pontofrio
    artifact.spinnaker.io/type: kubernetes/deployment
    artifact.spinnaker.io/version: ""
    deployment.kubernetes.io/revision: "186"
    devops.k8s.io/branch: release/3.21
    devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
    devops.k8s.io/component-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-name: cnova-preco
    devops.k8s.io/component-plataform: 'Baixa '
    devops.k8s.io/component-repository-url: https://github.com/viavarejo-internal/cnova-preco
    devops.k8s.io/component-squad: SQ PREÇO
    devops.k8s.io/component-system0-description: ""
    devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
    devops.k8s.io/component-system0-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-system0-name: '[Serviço de Preço]'
    devops.k8s.io/component-system0-product0-description: Ser uma plataforma que centralize
      todas as precificações 1P, em todos os canais da companhia, bem como gerenciar
      possíveis divergências de Preços para que o Comercial e Pricing tenham visão
      completa para tomada de decisão.
    devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
    devops.k8s.io/component-system0-product0-journey: JN INTELIGÊNCIA COMERCIAL
    devops.k8s.io/component-system0-product0-name: Precificação de Produto
    devops.k8s.io/component-tribe: TB PREÇO
    devops.k8s.io/flag: via
    devops.k8s.io/nexus-url: https://nexus.viavarejo.com.br/repository/charts/api-preco-b2c/3.21-1/deploy-via-hlg.yaml
    devops.k8s.io/project-name: api-preco-b2c
    devops.k8s.io/repository: api-preco-b2c
    devops.k8s.io/servicenow-task-number: CHG0316585
    devops.k8s.io/spinnaker: "true"
    devops.k8s.io/squad: Preço
    devops.k8s.io/tribe: Inteligência Comercial
    devops.k8s.io/version: 3.21-1
    devops.k8s.io/xl-release-start-date: Mon Apr 22 08:45:06 BRT 2024
    devops.k8s.io/xl-release-title: '[Preço] api-preco-b2c - 3.21-1'
    moniker.spinnaker.io/application: pricing
    moniker.spinnaker.io/cluster: deployment api-preco-pontofrio
    strategy.spinnaker.io/versioned: "false"
    viavarejo.com.br/app: api-preco
    viavarejo.com.br/environment: hlg
    viavarejo.com.br/team: pricing
  labels:
    app: api-preco-pontofrio
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: hlg
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: pricing
    app.kubernetes.io/part-of: api-preco-pontofrio
    app.kubernetes.io/project-name: api-preco-b2c
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 3-21-1
    devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
    devops.k8s.io/component-journey: jn-inteligencia-comercial
    devops.k8s.io/component-name: cnova-preco
    devops.k8s.io/component-plataform: baixa
    devops.k8s.io/component-squad: sq-preco
    devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
    devops.k8s.io/component-system0-journey: jn-inteligencia-comercial
    devops.k8s.io/component-system0-name: servico-de-preco
    devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
    devops.k8s.io/component-system0-product0-journey: jn-inteligencia-comercial
    devops.k8s.io/component-system0-product0-name: precificacao-de-produto
    devops.k8s.io/component-tribe: tb-preco
    k8slens-edit-resource-version: v1
  name: api-preco-pontofrio
  namespace: api-preco-b2c-hlg
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-preco-pontofrio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: api-preco-b2c-hlg
        artifact.spinnaker.io/name: api-preco-pontofrio
        artifact.spinnaker.io/type: kubernetes/deployment
        artifact.spinnaker.io/version: ""
        devops.k8s.io/branch: release/3.21
        devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
        devops.k8s.io/component-journey: JN INTELIGÊNCIA COMERCIAL
        devops.k8s.io/component-name: cnova-preco
        devops.k8s.io/component-plataform: 'Baixa '
        devops.k8s.io/component-repository-url: https://github.com/viavarejo-internal/cnova-preco
        devops.k8s.io/component-squad: SQ PREÇO
        devops.k8s.io/component-system0-description: ""
        devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
        devops.k8s.io/component-system0-journey: JN INTELIGÊNCIA COMERCIAL
        devops.k8s.io/component-system0-name: '[Serviço de Preço]'
        devops.k8s.io/component-system0-product0-description: Ser uma plataforma que
          centralize todas as precificações 1P, em todos os canais da companhia, bem
          como gerenciar possíveis divergências de Preços para que o Comercial e Pricing
          tenham visão completa para tomada de decisão.
        devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
        devops.k8s.io/component-system0-product0-journey: JN INTELIGÊNCIA COMERCIAL
        devops.k8s.io/component-system0-product0-name: Precificação de Produto
        devops.k8s.io/component-tribe: TB PREÇO
        devops.k8s.io/flag: via
        devops.k8s.io/nexus-url: https://nexus.viavarejo.com.br/repository/charts/api-preco-b2c/3.21-1/deploy-via-hlg.yaml
        devops.k8s.io/project-name: api-preco-b2c
        devops.k8s.io/repository: api-preco-b2c
        devops.k8s.io/servicenow-task-number: CHG0316585
        devops.k8s.io/spinnaker: "true"
        devops.k8s.io/squad: Preço
        devops.k8s.io/tribe: Inteligência Comercial
        devops.k8s.io/version: 3.21-1
        devops.k8s.io/xl-release-start-date: Mon Apr 22 08:45:06 BRT 2024
        devops.k8s.io/xl-release-title: '[Preço] api-preco-b2c - 3.21-1'
        kubectl.kubernetes.io/restartedAt: "2024-04-04T17:44:18Z"
        moniker.spinnaker.io/application: pricing
        moniker.spinnaker.io/cluster: deployment api-preco-pontofrio
        strategy.spinnaker.io/versioned: "false"
        viavarejo.com.br/app: api-preco
        viavarejo.com.br/team: pricing
      creationTimestamp: null
      labels:
        app: api-preco-pontofrio
        app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
        app.kubernetes.io/environment: hlg
        app.kubernetes.io/managed-by: spinnaker
        app.kubernetes.io/name: pricing
        app.kubernetes.io/part-of: api-preco-pontofrio
        app.kubernetes.io/project-name: api-preco-b2c
        app.kubernetes.io/stage: stable
        app.kubernetes.io/version: 3-21-1
        devops.k8s.io/component-id: 9a277506-7244-45ed-9713-1388f0755c15
        devops.k8s.io/component-journey: jn-inteligencia-comercial
        devops.k8s.io/component-name: cnova-preco
        devops.k8s.io/component-plataform: baixa
        devops.k8s.io/component-squad: sq-preco
        devops.k8s.io/component-system0-id: 1c7ea6fa-c95e-481a-b1f0-6609c0a69120
        devops.k8s.io/component-system0-journey: jn-inteligencia-comercial
        devops.k8s.io/component-system0-name: servico-de-preco
        devops.k8s.io/component-system0-product0-id: 4d552446-6825-4d51-9976-362156f21c22
        devops.k8s.io/component-system0-product0-journey: jn-inteligencia-comercial
        devops.k8s.io/component-system0-product0-name: precificacao-de-produto
        devops.k8s.io/component-tribe: tb-preco
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.azure.com/scalesetpriority
                operator: In
                values:
                - spot
            weight: 1
      containers:
      - envFrom:
        - configMapRef:
            name: api-preco-pontofrio
        image: harbor01.viavarejo.com.br/pricing/api-preco-b2c:3.21-1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: web
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 20
        name: api-preco-pontofrio
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - catalogo.pontofrio.com.br
        ip: 10.106.24.18
      nodeSelector:
        app: pricing
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
