apiVersion: v1
data:
  SECURITY_JWT_CLIENT_ID: c2Ftc3VuZ2FwcA==
  SECURITY_JWT_CLIENT_SECRET: JDJhJDEwJEptREpnbS5IZGIvcTRBOXRqS1U3YS5qc0dibHllVFIwSEFTcDBuRGg4QlN2bE5kSEN6M0dH
  SECURITY_JWT_SIGNING_KEY: Y29tZXJjaWFsYm9uaWZpY2FjYW8=
kind: Secret
metadata:
  name: jwt-bonificacao
  namespace: bonificacao-prd
type: Opaque
