apiVersion: v1
data:
  LN_DATASOURCE_DRIVER_CLASS_NAME: Y29tLmlibS5kYjIuamNjLkRCMkRyaXZlcg==
  LN_DATASOURCE_PASSWORD: M2o1MGZ1b3Q=
  LN_DATASOURCE_URL: amRiYzpkYjI6Ly8xMC4yMjguMTAuNTA6NTAwMDAvQkFBTg==
  LN_DATASOURCE_USERNAME: Ym9uaWZpYw==
  LN_TEST_WHILE_IDLE: dHJ1ZQ==
  LN_VALIDATION_QUERY: U0VMRUNUIDE=
kind: Secret
metadata:
  name: ln-bonificacao
  namespace: bonificacao-prd
type: Opaque
