apiVersion: v1
kind: Service
metadata:
  annotations:
    app.via.com.br/branch: release/2.5.0
    app.via.com.br/flag: via
    app.via.com.br/nexus-url: https://nexus.viavarejo.com.br/repository/charts/comercial-bonificacao-redesign-ngx/2.5.0-41/deploy-via-prd.yaml
    app.via.com.br/project-name: comercial-bonificacao-redesign-ngx
    app.via.com.br/repository: comercial-bonificacao-redesign-ngx
    app.via.com.br/servicenow-task-number: CHG0307852
    app.via.com.br/spinnaker: "true"
    app.via.com.br/squad: Bonificação
    app.via.com.br/tribe: Inteligência Comercial
    app.via.com.br/version: 2.5.0-41
    app.via.com.br/xl-release-start-date: Wed Mar 06 13:14:16 BRT 2024
    app.via.com.br/xl-release-title: '[Bonificacao] comercial-bonificacao-redesign-ngx
      - 2.5.0-41'
    artifact.spinnaker.io/location: bonificacao-prd
    artifact.spinnaker.io/name: comercial-bonificacao-redesign-ngx
    artifact.spinnaker.io/type: kubernetes/service
    artifact.spinnaker.io/version: ""
    moniker.spinnaker.io/application: bonificacao
    moniker.spinnaker.io/cluster: service comercial-bonificacao-redesign-ngx
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: comercial-bonificacao-redesign-ngx
    app.kubernetes.io/deployed-by: spinnaker-artifact-nexus
    app.kubernetes.io/environment: prd
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: bonificacao
    app.kubernetes.io/part-of: comercial-bonificacao-redesign-ngx
    app.kubernetes.io/project-name: comercial-bonificacao-redesign-ngx
    app.kubernetes.io/stage: stable
    app.kubernetes.io/version: 2.5.0-41
  name: comercial-bonificacao-redesign-ngx
  namespace: bonificacao-prd
spec:
  clusterIP: 10.2.0.131
  clusterIPs:
  - 10.2.0.131
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-tcp
    port: 80
    targetPort: 8080
  selector:
    app: comercial-bonificacao-redesign-ngx
    deploymentconfig: comercial-bonificacao-redesign-ngx
