apiVersion: v1
kind: Service
metadata:
  labels:
    app: comercial-bonificacao-pgbouncer
  name: comercial-bonificacao-pgbouncer
  namespace: bonificacao-prd
spec:
  clusterIP: 10.2.0.96
  clusterIPs:
  - 10.2.0.96
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
  selector:
    app: comercial-bonificacao-pgbouncer
