apiVersion: v1
kind: Service
metadata:
  labels:
    app: comercial-bonificacao-api
  name: comercial-bonificacao-scheduler-cb
  namespace: bonificacao-prd
spec:
  clusterIP: 10.2.0.242
  clusterIPs:
  - 10.2.0.242
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-tcp
    port: 80
    targetPort: 8080
  - name: 8090-tcp
    port: 8090
  selector:
    app: comercial-bonificacao-api
    deploymentconfig: comercial-bonificacao-scheduler-cb
